---
# tasks file for ansible-role-amazon-ssm

- name: Include OS specific variables.
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Install aws ssm agent
  ansible.builtin.include_tasks: "setup-{{ ansible_facts['os_family'] }}.yml"

- name: Managing ssm-user account permissions
  ansible.builtin.include_tasks: ssm-user.yml
  when: ansible_facts['system'] != "Win32NT"

- name: Register on-premise hosts
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', register_files) }}"
  vars:
    register_files:
      - "tasks/register-{{ ansible_facts['system'] }}.yml"
      - "tasks/register-Linux-Unix.yml"
  when:
    - activation_code is not none
    - activation_id is not none
    - aws_region is not none

- name: Configure proxy
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', proxy_files) }}"
  vars:
    proxy_files:
      - "tasks/proxy-{{ ansible_facts['system'] }}.yml"
      - "tasks/proxy-Linux-Unix.yml"
  when:
    - (http_proxy_url is not none) or (https_proxy_url is not none)
