---
# Register on-premise Windows host to amazon ssm
# https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-managedinstances.html

- name: Windows | Register on-premise host
  ansible.windows.win_package:
    path: "{{ ssm_package_url }}"
    product_id: amazon-ssm-agent
    creates_path: C:\Program Files\Amazon\SSM\amazon-ssm-agent.exe
    arguments:
      - /q
      - /log install.log
      - CODE={{ activation_code }}
      - ID={{ activation_id }}
      - REGION={{ aws_region }}
      - -Wait
    state: present
