---
# Install aws ssm agent on RedHat family system

- name: RedHat | Install aws ssm agent
  ansible.builtin.dnf:
    name: "{{ ssm_package_url }}"
    disable_gpg_check: true # https://github.com/aws/amazon-ssm-agent/issues/235
    state: present

- name: RedHat | Manage aws ssm agent service
  ansible.builtin.service:
    name: "{{ ssm_service }}"
    state: started
    enabled: true
