---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: linux
    image: ${namespace:-diodonfrost}/${image:-ansible-ubuntu:24.04}
    command: ${cmd:-"sleep 999"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
verifier:
  name: ansible
