---
- name: Verify
  hosts: all
  tasks:
    - name: Windows | Amazon ssm agent service should be started and enabled
      ansible.windows.win_service:
        name: AmazonSSMAgent
        start_mode: auto
        state: started
      register: ssm_service_result

    - name: Windows | Verify commands outputs
      ansible.builtin.assert:
        that:
          - not ssm_service_result.changed
        success_msg: "All tests passed"
